### ISSUE TITLE
Are the statistical analysis vignettes referenced in the README actually included in the SomaDataIO package?

### ISSUE THREAD

**Issue by nmcnulty** [SomaLogic/SomaDataIO#123]
Hi SomaDataIO Devs,

Both the release notes for `6.1.0` and the current README reference the existence of vignettes that illustrate four types of primary analyses that are commonly performed on SomaScan data (i.e., pairwise _t_-tests, multi-group ANOVA, linear regression, and binary classification). I haven't been able to find those vignettes in `6.1.0`. I'm not sure if I'm trying to pull them up incorrectly, or if they weren't actually included in the `6.1.0` release. I _do_ see an 'Introduction to SomaDataIO' vignette (which itself references the vignettes above), but nothing else.

Here's my command:
```r
vignette(package="SomaDataIO")
```

Here's the output:
```
Vignettes in package ‘SomaDataIO’:

SomaDataIO                             Introduction to SomaDataIO (source, html)
```

Thanks!

Nate

**Comment by scheidec** [comment]
Hi Nate! Thanks for bringing this to our attention.  In an effort to reduce dependencies introduced by the vignette tutorials to the package, all of the `SomaDataIO` help pages are actually "articles" instead of true vignettes included with the package when installed.  So they are accessible on our `pkgdown` website only.  See here for details: https://r-pkgs.org/vignettes.html#sec-vignettes-article

Though, your finding does show that our current README and pkgdown introduction landing page are a bit misleading when calling out the code typically used to reference the vignettes, that does not work when they are articles instead and not included along with the package.  We will update those references to use links to the website tutorial pages instead, and add some clarity in the documentation on those pages that these "articles/workflows" are only available on the `pkgdown` website and not accessible through the installed package.
