### ISSUE TITLE
When I  loaded my .adat file, it reported "Error: At least some values are not in 'SeqId' format."

### ISSUE THREAD

**Issue by kf-wei** [SomaLogic/SomaDataIO#127]
Hello, 

I was using SomaDataIO to read my .adat file.

There were something wrong in the adat file so that the warnings as following appeared:

Error: At least some values are not in 'SeqId' format.
Try running `getSeqId()` for: NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 

I had tried to some fixing according to the sample file but failed.

I don't know what's the key problem causing this erro and pretty hope to fix it.

I would appreciate if there were some suggestions.

".txt" was added to the file's name to upload.

[try.adat.txt](https://github.com/user-attachments/files/15898425/try.adat.txt)

**Comment by m-gall** [comment]
Hi Kf-wei,
Based on the 'try.adat.txt' file you provided, I can see that some SeqIds may have been mutated into 'dates' and so they no longer match the keys stored in SomaDataIO. My guess is this might happen if the file has been manipulated and saved in a program like Excel.
I would suggest trying to import a fresh copy of the original adat file and see whether the same error occurs.
I hope this solves the problem! :)

**Comment by m-gall** [comment]
Adding more information to this issue, for others benefit.
The issue described above relates to opening the adat file in Excel.
From what I can gather, Excel appears to make decisions for correct date formatting, based on your local computer settings.
If your computers date format is set with year leading (e.g. YYYY-MM-DD) since a SeqID like 9999-1 looks similar to a YYYY-MM date format, it will parse the value to Jan-99.
