### ISSUE TITLE
How to perform differential expression from SomaLogic files

### ISSUE THREAD

**Issue by Foinhaven** [SomaLogic/SomaDataIO#128]
## The Problem

Hi and thanks in advance. I am working with a SomaLogic file from 5 years ago, with proteomic data derived from serum samples. The file is in the standard SomaLogic format - I have included the list of initial headings at the bottom. My understanding is that this is normalised protein read counts in RFU. The file was in .adat format, but I received it in .csv format.

My question is - what method/package in R would be best for creating a differential expression table from this data? I have been using the limma function, which appears to have worked, but I wished to check that this is what you would advise. 

The project is looking at the differences between samples X and Y. I have copied my code below. I have created a sample sheet "ss", delineating X and Y, where SAMPLEGROUP is either X or Y. The file from SomaLogic has been imported as "em"

## R code
Please describe your question with R code (if possible):
```r
# Create a design matrix for the linear model
# Convert SAMPLEGROUP to a factor
ss$SAMPLEGROUP <- factor(ss$SAMPLEGROUP, levels = c("X", "Y"))

# Create the design matrix
design <- model.matrix(~ 0 + ss$SAMPLEGROUP)
colnames(design) <- levels(ss$SAMPLEGROUP)

# Check the design matrix
design

# Fit the linear model
fit = lmFit(em, design)

# Create a contrast matrix to compare X and Y
contrast.matrix <- makeContrasts(XvsY = X - Y, levels = design)

# Fit the contrasts
fit2 <- contrasts.fit(fit, contrast.matrix)
fit2 <- eBayes(fit2)

# Get the top differentially expressed proteins
topTable(fit2)

# Extract the differential expression results
results <- topTable(fit2, adjust = "BH", number = Inf)

# Select specific columns: log2 fold change, p-value, adjusted p-value
de <- results[, c("logFC", "P.Value", "adj.P.Val")]
```

---

Thank you for using `SomaDataIO` :pray:!

**Comment by wschwarzmann** [comment]
Hello @Foinhaven , I am a bioinformatician from SomaLogic's Global Scientific Engagement team, and I can answer your question! You are correct, the data is the normalized linear RFU values. Limma is certainly a way to achieve a differential expression table. There is a step to modify when using on SomaScan data, however. As variance between dilution levels is different on the SomaScan assay, the eBayes() method Limma suggests for gene expression data does not work well for SomaScan data. Thus, we would recommend excluding your `fit2 <- eBayes(fit2)` line. 

We have a workflow for building a differential expression table here: https://somalogic.github.io/SomaDataIO/articles/stat-two-group-comparison.html
This is designed around the .adat file, but it would seem that your .csv file is structured similarly, so it should be adaptable! The one thing absent from the vignette published is calculating the Log2 fold change. To do so, we use a formula like:
`log2FC <- log2(median(adat[Group = "GroupB",]) / median(adat[Group = "GroupA",]))`
where adat is the adat object (or csv table in your case) containing the linear RFU values. In this case, as compared to the workflow proposed in our vignette, we go back to the linear RFU values and calculate the Log2 fold change, rather than calculating the fold change on the log10 values used for the statistical tests (as this would produce very small fold changes).

I hope this answer has been helpful! For questions about the package and functions within, feel free to open another GitHub issue. For questions about conducting analysis, you can email techsupport@somalogic.com and a bioinformatician from our team will reply.

**Comment by Foinhaven** [comment]
Thanks @wschwarzmann 

The issue with what you have suggested is that by removing the  `fit2 <- eBayes(fit2)` line, limma cannot proceed and the error message received is "Error in topTable(fit2) : Need to run eBayes or treat first"

I have progressed my code however when I do this, I notice that the Log2Fold is incorrect. The volcano plots look okay, but the Log2Fold is in the thousands. I presume this is due to that RFU need normalisation in some form - please could you explain how to do this and at which step?
To be clear, the RFU readings vary from the hundreds (675) to the thousands (70,657). The LogFC also vary from -20,000 to +15000.

I have put the rest of my code down for clarity.

```
#Load EM and SS#
em = read.table("etc...")
ss = read.table("etc...")

# Ensure the sample names in ss match the column names in EM
all(ss$sample %in% colnames(em))

#differential expression #

# Design matrix for the linear model
# Convert SAMPLEGROUP to a factor
ss$SAMPLEGROUP <- factor(ss$SAMPLEGROUP, levels = c("X", "Y"))

# Create the design matrix
design <- model.matrix(~ 0 + ss$SAMPLEGROUP)
colnames(design) <- levels(ss$SAMPLEGROUP)

# Fit the linear model
fit = lmFit(em, design)

# Create a contrast matrix to compare X and Y
contrast.matrix <- makeContrasts(XvsY = X - Y, levels = design)

# Fit the contrasts
fit2 <- contrasts.fit(fit, contrast.matrix)
fit2 <- eBayes(fit2)

# Get the top differentially expressed genes
topTable(fit2)

# Extract the differential expression results
results <- topTable(fit2, adjust = "BH", number = Inf)

# Select specific columns: log2 fold change, p-value, adjusted p-value
de <- results[, c("logFC", "P.Value", "adj.P.Val")]

# Rename columns for clarity
colnames(de) <- c("log2fold", "p", "p.adj")

#Parse
master=merge(em, de,by.x=0,by.y=0)

row.names(master)=master[,1]

master=na.omit(master)

em_symbols=master[,2:203]

master_sorted=order(master[,"p.adj"],decreasing=FALSE)

master=master[master_sorted,]

master$MeanExpression=rowMeans(master[,c(2:203)])

master$mlog10p=master[,"p.adj"]
master$mlog10p=-log10(master$p.adj)

master$sig = as.factor(master$p.adj<0.05 & abs(master$log2fold)>1.0)

em_scaled = data.frame(t(scale(t(em_symbols))))

master_sig=subset(master,p.adj<0.05 & abs(master$log2fold)>1.0)

#3.11 Create Dataframe of Significant Genes, then Create and Scale EM of Significant Genes
sig_genes=row.names(master_sig)
data.frame(sig_genes)
em_symbols_sig=em_symbols[sig_genes,]
em_scaled_sig = data.frame(t(scale(t(em_symbols_sig))))

#3.13 Rename row.names to SYMBOL
colnames(master) = c("SYMBOL", colnames(master)[-1])

#3.12 Create Subset of Up/Down Regulated Genes and of Top 5 in those Categories
master_sig_up   = subset(master, p.adj < 0.05 & log2fold >1)
master_sig_down = subset(master, p.adj < 0.05 & log2fold < -1)
master_sig_up_top5 = master_sig_up[1:5,]
master_sig_down_top5 = master_sig_down[1:5,]`
```

**Comment by wschwarzmann** [comment]
Hi @Foinhaven , you can bypass the eBayes error, but pulling out the t-statistic and p-value separately. Try something like this:
```
fit2$t_alt <- fit2$coef/fit2$stdev.unscaled/fit2$sigma
fit2$p.value_alt <- 2 * pt(-abs(fit2$t), df = fit2$df.residual)
```
The RFU range you report seems reasonable in terms of the whole proteome. For an individual analyte that would be large, but not even entirely out of the question by our typical calculations (of the lower and higher values you reported were the medians, that would be a Log2 FC of 6.5). The typical formula we would use is:
Log2( median(GroupB) / median(GroupA) ) 
This is assuming the GroupA and B values are the linear RFU values. This could have something to do with the way limma calculates the fold change. 
You are also correct in terms of statistics though on needing some pre-processing due to the large range of values. Typically, we would recommend log10-transforming and center-scaling the linear RFU values before running model.matrix(). You can find some of these pre-processing steps in the vignette here:
https://somalogic.github.io/SomaDataIO/articles/stat-two-group-comparison.html
Let me know if this is helpful!
