### ISSUE TITLE
Trouble Parsing ADAT File

### ISSUE THREAD

**Issue by ruhinaik** [SomaLogic/SomaDataIO#17]
Hi,

Thanks for creating this great tool! I am having trouble reading in the full dataset from my ADAT file. There should be 2100 rows being read in, but only 2080 are being processed from using the read_adat() function. While the data is being parsed, it says there are 3 parsing failures. I am also using v5 of the package, would you recommend using an older version?

Here is the following error:
> my_adat <- read_adat("./somalogic_files/SS-215184.v4.1.EDTA Plasma.hybNorm.medNormInt.plateScale.calibrate.anmlQC.qcCheck.ext.adat")
3 parsing failures.
 row col           expected                                                                               actual                                                                                                           file
1129 X17 1/0/T/F/TRUE/FALSE Leak                                                                                 './somalogic_files/SS-215184.v4.1.EDTA Plasma.hybNorm.medNormInt.plateScale.calibrate.anmlQC.qcCheck.ext.adat'
1311 X17 1/0/T/F/TRUE/FALSE Low volume transfer from sample rack to Dil 1 plate and from Dil 1 to Catch 0 plate. './somalogic_files/SS-215184.v4.1.EDTA Plasma.hybNorm.medNormInt.plateScale.calibrate.anmlQC.qcCheck.ext.adat'
1548 X17 1/0/T/F/TRUE/FALSE Leak                                                                                 './somalogic_files/SS-215184.v4.1.EDTA Plasma.hybNorm.medNormInt.plateScale.calibrate.anmlQC.qcCheck.ext.adat'

Hope you can help with this! Thank you in advance.

**Comment by stufield** [comment]
Hi @ruhinaik , this looks to be coming from the `readr` package ... seems like a column of data (17th?), goes from `0/1` to `T/F`. Not sure exactly, but the parsing logic in `readr` is getting confused by the switch in format.

Since you're already working with an older version of SomaDataIO (`v5.0`) I'd actually recommend upgrading to a newer version, since in `v5.2.0` we moved away from the `readr` package (partly due to this parsing issue). The current version `v5.3.0` has some additional bug fixes and improvements. 

If you do not want to upgrade, there it is possible to pass arguments to the `readr::read_delim()` function via the `...`, to help in the parsing (which sometimes solves the issue). Namely try:
```
read_adat("file.adat", guess_max = 2100)    # default is 1000
```

Also, I would check the ADAT file itself and confirm what's going on with that variable. See the T/F and 0/1. It's just a tab delimited text file, so you can open in your favorite text editor (or even Excel ... but don't save it in Excel!). Opening a copy in Excel is often safest.

**Comment by ruhinaik** [comment]
Oh okay, thanks for your quick reply! Will try these solutions and get back to you.

**Comment by ruhinaik** [comment]
There were no parsing issues after changing the version to v5.2.0! 

It also turns out when looking at the ADAT file on Excel, there were only 2081 rows in the file given, so no data was actually lost when reading it in with read_adat() function. Thanks so much for your help!
