### ISSUE TITLE
Conversion of data frame to .adat format and applying ANOVA

### ISSUE THREAD

**Issue by Manonanthini** [SomaLogic/SomaDataIO#22]
Hi 
In my project, I have to add 3 other columns to my data and I have to apply ANOVA to compare the means between protein quantification or expression. If I add a column to my data based on SampleId, my .adat became data frame and couldn't find ways to convert back to .adat, but it applies all functions of adat like getAnalyteinfo() if I copy the attributes from original adat data to newly created dataframe. I could understand it is wrong but trying in different ways before contacting you

Please guide me in both issues.

Best regards
Mano

**Comment by stufield** [comment]
Thanks for the question. You shouldn't have to do anything special to add a column (variable) to your `soma_adat` data frame, and you shouldn't lose the `soma_adat` class in the process. 

1. are you sure you have loaded `SomaDataIO` with `library(SomaDataIO)`? There are methods there that are necessary to maintain the integrity of the `soma_adat` object.
2. can you provide a `reprex` so that I can see (and replicate) what you are doing? See https://www.tidyverse.org/help/

**Comment by Manonanthini** [comment]
Hi,
Thanks for the reply.

1. Could you please guide me on how to add a data frame object (which contain SampleId, Sex, Age, and BMI) with a soma_adat object ? I have used right join method listed in methods(soma_adat). Is there any method to preserve the class?
  
2. Could I use aov followed by Tukeyhsd() for performing ANOVA and multiple comparision analysis? or is there any specific method available for the Soma analysis?

3. Do we have to preserve the class as soma_adat till the end of analysis? 

4. I have been performing a replication of Olink statistical analysis in Soma adat?

Thanks in advance.

Best regards
Mano

**Comment by stufield** [comment]
Hi,

1. I recommend using `left_join()` to merge in clinical data into a `soma_adat`, this is because the class of `x` is what's maintained in the returned object (not `y`). Which usually I want to be my `soma_adat`.

```
reprex::reprex({
  library(SomaDataIO)
  dim(example_data)
  class(example_data)
  clin <- data.frame(SampleId = as.character(1:192),
                     height   = rnorm(192, 100))
  left <- left_join(example_data, clin, by = "SampleId")
  dim(left)
  class(left)
  
  class(right_join(clin, example_data, by = "SampleId"))
})
```

This preserves the `soma_adat` class, but the `right_join()` preserves the `data.frame` class (`clin`).

2. There is a full example in the `README` (landing page for GitHub) on how I would do this (tho it's using a t-test). I recommend using a [List Columns](https://jennybc.github.io/purrr-tutorial/ls13_list-columns.html) approach.

3. You don't *have* to maintain the `soma_adat` class, but I highly recommend it because there are many methods for the class under the hood that you can/should make use of.

I think to assist you further I will need to see a `reprex` of exactly what you're doing. Please ensure it contains the minimal data/information that reproduces the behavior you're seeing (doesn't have to be YOUR data).

Cheers,
Stu

**Comment by Manonanthini** [comment]
Hi,
Thanks for the reply and suggestion. I have now created the adat file with anova details.
But I couldn't do pairwise ancova (i have to adjust for covariates also) for multiple comparisons.
Could you please help me out with the analysis?

I have herewith attached my code for your kind reference. I have used 'ListColumns' approach for mapping F statistics and P.value as per your suggestion. ANOVA model creates is a list and couldn't be applied to any multiple comparison function, and I also get the error "no model matrix function is available for the model created". Please guide.

Thanks a lot. 

Best regards
Manonanthini

library(dplyr)
library(SomaDataIO)
library(purrr)
library(tidyverse)
library(rstatix)
library(multcomp)
f <- "new.adat"
my_adat <- read_adat(f)
levels(df2$group)
df_adat=SomaDataIO::left_join(my_adat,df2,by="SampleId")
class(df_adat)

names(attributes(df_adat))
#[1] "names"       "class"       "row.names"   "Header.Meta" "Col.Meta"    "file_specs"  "row_meta" 
names(attributes(my_adat))
#[1] "names"       "class"       "row.names"   "Header.Meta" "Col.Meta"    "file_specs"  "row_meta"   
df_clean <- df_adat %>% filter(if_all(everything(), ~ !is.na(df_adat$group))) 
df_clean=subset(df_clean, group != "1")
table(df_clean$group)

df_final=getAnalyteInfo(df_clean) %>% 
  select(AptName, SeqId, Target = TargetFullName, EntrezGeneSymbol, UniProt)

df_final4 <- df_final %>% 
  mutate(formula = map(AptName, ~ as.formula(paste(.x, "~ group+Sex:Age:BMI"))), # create formula
         model1  = map(formula, ~ stats::anova(lm(.x,data = df_clean))),
         F.value  = map(model1, "F value"),            # pull out F-statistic
         p.value = map(model1, "Pr(>F)"),    # pull out p-values
         fdr     = p.adjust(sapply(p.value,'[[',1),n = length(p.value), method = "bonferroni"))    %>%
  arrange(sapply(p.value,'[[',1)) %>%           # re-order by `p-value`
  mutate(rank = row_number())

df_final5 <- df_final %>% 
  mutate(formula = map(AptName, ~ as.formula(paste(.x, "~ group+Sex:Age:BMI"))), # create formula
         model1  = map(formula, ~ stats::anova(stats::lm(.x,data = df_clean))),
#         tukey <- pairw.anova(y = AptName, x = group, method = "tukey")

**Comment by stufield** [comment]
Hi @Manonanthini ,

The code you provided cannot be run on another machine, thus I cannot reproduce the error locally.

Please provide a [reprex](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) with the **minimal** set of requirements necessary to reliably reproduce the error you're experiencing. The `mtcars` or `iris` data sets can be useful here. Please make it clear and minimal, with no extraneous code. Just what's necessary to re-create the error.

**Comment by Manonanthini** [comment]
Hi,
Thanks for the reply and suggestion. I have now created the adat file with anova details.
But I couldn't do pairwise ancova (i have to adjust for covariates also) for multiple comparisons.
Could you please help me out with the analysis?

I have herewith attached the reprex render() for your kind reference. ANOVA model created was a list and couldn't be applied to any multiple comparison function, and I also get the error "no model matrix function is available for the model created". Please guide.

Thanks a lot.

Best regards
Manonanthini

df_final10 <- df_final %>%
mutate(formula = map(AptName, ~ as.formula(paste(.x, "~ Cluster+Sex:Age_onset:BMI"))),
model1 = map(formula, ~ stats::anova(lm(.x,data = df_clean))),
F.value = map(model1, "F value"),
p.value = map(model1, "Pr(>F)"),
fdr = p.adjust(sapply(p.value,'[[',1),n = length(p.value), method = "bonferroni")
) %>%
mutate(rank = row_number())
#> Error in df_final %>% mutate(formula = map(AptName, ~as.formula(paste(.x, : could not find function "%>%"

df_final5 <- df_final %>% dplyr::mutate(formula = map(AptName, ~ as.formula(paste(.x, "~ Cluster+Sex:Age_onset:BMI"))), # create formula
model1 = map(formula, ~ stats::anova(stats::aov(.x,data = df_clean))),
tukey <- pairw.anova(y = AptName, x = Cluster, method = "tukey"))
#> Error in df_final %>% dplyr::mutate(formula = map(AptName, ~as.formula(paste(.x, : could not find function "%>%"

Created on 2022-08-25 with [reprex v2.0.2](https://reprex.tidyverse.org/)

**Comment by stufield** [comment]
@Manonanthini ,

The `reprex` you provided does not produce the error you describe (fails on a `magrittr` pipe error since you didn't include it in the `reprex`). However, this is not the main problem ... in your example `df_final` does not exist, therefore this code is not run-able on anyone else's machine. Please follow the directions on how to write a `reprex` [here](https://reprex.tidyverse.org/articles/).

Additionally, this is not a MINIMAL example. I have suggested using a general data set like `iris` or `mtcars`, and ONLY performing the function calls that are necessary to replicate the error you are experiencing.

Writing a valid `reprex` can be challenging, but it helps me help you. And if I cannot reproduce your error, it is very difficult for me to help you. Good luck.

**Comment by Manonanthini** [comment]
Hi Stu,
I have two files. I have a dataframe with age, BMI, and Sex,
treatment_outcome with sampleid and another adat file with Somalogic
protein quantification.
Now,my job is to adjust for covariates Sex,age and BMI as well as do an
anova for 4 factor levels of treatment_outcomes.
I tried initially using aov with a merged data frame from read.adat and
data frame. As the data is highly confidential, I couldn't share it with
you. I apologize for that.
Could you please guide me the steps to do anova? The formula i used is
Aptname~ Outcome+Sex:Age:BMI.

Thanks and regards
Manonanthini Thangam


Thanks and Regards,
Manonanthini Thangam

**Comment by stufield** [comment]
Hello @Manonanthini ,

It seems your question has evolved into more of a model development in `R` analysis question, whereas this forum is designed to address issues related to the input/output (`I/O`) of SomaScan data from a software perspective. In that regard `SomaDataIO` appears to have satisfied your needs (you are now fitting models!). At this point I would direct you to a more general model fitting in `R` forum like:

-  [StackOverflow](https://stackoverflow.com)
-  [Stack Exchange/Cross Validated](https://stats.stackexchange.com)
-  [RStudio](https://community.rstudio.com)

Of course, if you feel the analysis in question is directly linked to SomaScan as a platform, I suggest contacting techsupport@somalogic.com for further assistance.
