### ISSUE TITLE
Flagged and Normal distribution

### ISSUE THREAD

**Issue by MoemenEltobgy** [SomaLogic/SomaDataIO#29]
Greetings,
I have 2 qestions while going through the SOmaDataIO tutorial guide:
1. if I am working on an adat file with 40 samples and some of them are flagged. Should I exclude them from the analysis or not? (I am using the "ANML" extension file).
2. for the same file: should I test it for normal distribution before running a t test? and if my data is skewed what's the proper alternative for an independent t test in that case? I already did a t test according to alive or dead but I need to make sure whether a non-parametric test is required or not.
thanks.
Thanks for using SomaDataIO!

**Comment by stufield** [comment]
Since this is less of a software question and more SomaScan analysis related, I will ask @wschwarzmann to reach out to you shortly regarding this issue. Thank you!

**Comment by wschwarzmann** [comment]
Hello @MoemenEltobgy . My name is Will from SomaLogic's Global Scientific Engagement team, and I'd be happy to help answer your questions.

1. SomaLogic flags samples that are outside of our acceptance criteria at particular normalization steps (these criteria can be found in the SomaScan Quality Statement .pdf file). Flagging samples is a means of estimating samples that may be outliers, either due to technical issues with the assay, preparation of a given sample, or biological variance. To strictly adhere to the SomaLogic acceptance criteria, flagged samples should be excluded from analysis. However, samples flagged as potential outliers might make sense in the context of the study and could be worthy of including if associated with conditions observed.

2. You can, if desired, test the data for normal distribution before running a statistical test. Statistically speaking, a Mann-Whitney U-test would be more appropriate for skewed data. Depending on the design of the study though, a T-test could still be applicable. SomaLogic data can be non-normal depending on the conditions observed. 

I'd be happy to chat with you more about these specifics as they apply to your particular study. If you'd like to do so, please email techsupport@somalogic.com . Let them know your questions, and that you'd like to talk to Will further.
